
[functions.announcement-notification]
enabled = true
verify_jwt = true
import_map = "./functions/announcement-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/announcement-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/announcement-notification/*.html" ]

[functions.user-rsvp-admin-notification]
enabled = true
verify_jwt = true
import_map = "./functions/user-rsvp-admin-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/user-rsvp-admin-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/user-rsvp-admin-notification/*.html" ]
